[project]
name = "pyhthonwa-markdown-layer"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.13"

dependencies = [
  "markdown~=3.6",
]


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
